@port = 4000
@api = http://localhost:{{port}}/api/v1/type

### get all
GET {{api}}

### get
GET {{api}}/100

### create
POST {{api}}
Content-Type: application/json

{ 
  "title": "Vip102",
  "costPerMinute": 100.00
}

### delete
DELETE {{api}}/19

### update
PUT {{api}}/7
Content-Type: application/json

{
  "title": "Vip241",
  "costPerMinute": 0.05
}