
@port = 4000

### api-register-vehicle
@api1 = http://localhost:{{port}}/api/v1/register-vehicle/

### entryVehicleRecord 
POST {{api1}}
Content-Type: application/json

{ 
  "licensePlate": "YTQ-852" 
}

### exitVehicleRecord
PUT {{api1}}
Content-Type: application/json

{
  "licensePlate": "YTQ-852"
}




