@port = 4000
@api = http://localhost:{{port}}/api/v1/vehicle

### get all
GET {{api}}

### get
GET {{api}}/1

### create
POST {{api}}
Content-Type: application/json

{ 
  "licensePlate": "ASD-123",
  "typeId": 1
}

### delete
DELETE {{api}}/5

### update
PUT {{api}}/7
Content-Type: application/json

{
  "licensePlate": "DAT-098",
  "typeId": 1
}